LOCATION_MAPPING = {
    [0x196a4] = "@The Great Sea/Outset Island Sector/Outset Island/Under Link's House",
    [0x196a5] = "@The Great Sea/Outset Island Sector/Outset Island/Mesa's House Chest",
    [0x196a6] = "@The Great Sea/Outset Island Sector/Outset Island/Orca Give 10 Knight's Crests",
    [0x196a8] = "@The Great Sea/Outset Island Sector/Outset Island/Great Fairy",
    [0x196a9] = "@The Great Sea/Outset Island Sector/Outset Island/Jabun's Cave Chest",
    [0x196aa] = "@The Great Sea/Outset Island Sector/Outset Island/Dig up Black Soil",
    [0x196ab] = "@The Great Sea/Outset Island Sector/Outset Island/Savage Labyrinth Floor 30",
    [0x196ac] = "@The Great Sea/Outset Island Sector/Outset Island/Savage Labyrinth Floor 50",

    [0x196ad] = "@The Great Sea (Deprecated)/Windfall Island - Free/Jail - Tingle - First Gift",
    [0x196ae] = "@The Great Sea (Deprecated)/Windfall Island - Free/Jail - Tingle - Second Gift",
    [0x196af] = "@The Great Sea (Deprecated)/Windfall Island - Free/Jail - Maze Chest",
    [0x196b0] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Chu Jelly Juice Shop - Give 15 Green Chu Jelly",
    [0x196b1] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Chu Jelly Juice Shop - Give 15 Blue Chu Jelly",
    [0x196b2] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Ivan - Catch Killer Bees",
    [0x196b3] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Mrs. Marie - Catch Killer Bees",
    [0x196b4] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Mrs. Marie - Give 1 Joy Pendant",
    [0x196b5] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Mrs. Marie - Give 21 Joy Pendants",
    [0x196b6] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Mrs. Marie - Give 40 Joy Pendants",
    [0x196b7] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Lenzo's House - Left Chest",
    [0x196b8] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Lenzo's House - Right Chest",
    [0x196b9] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Lenzo's House - Become Lenzo's Assistant",
    [0x196ba] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Lenzo's House - Bring Forest Firefly",
    [0x196bb] = "@The Great Sea (Deprecated)/Windfall Island - Free/House of Wealth Chest",
    [0x196bc] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Maggie's Father - Give 20 Skull Necklaces",
    [0x196bd] = "@The Great Sea (Deprecated)/Windfall Island - Free/Maggie - Free Item",
    [0x196be] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Maggie - Delivery Reward",
    [0x196bf] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Cafe Bar - Postman",
    [0x196c0] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Kreeb - Light Up Lighthouse",
    [0x196c1] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Transparent Chest",
    [0x196c2] = "@The Great Sea (Deprecated)/Windfall Island - Free/Tott - Teach Rhythm",
    [0x196c3] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/Pirate Ship",
    [0x196c4] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/5 Rupee Auction",
    [0x196c5] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/40 Rupee Auction",
    [0x196c6] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/60 Rupee Auction",
    [0x196c7] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/80 Rupee Auction",

    [0x197e4] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/100 Rupee Auction", -- HD exclusive auction location
    [0x197e5] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/Dampa Pig Minigame", -- HD exclusive Minigame location

    [0x196c8] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Zunari - Stock Exotic Flower in Zunari's Shop",
    [0x196c9] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Sam - Decorate the Town",
    [0x196ce] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Mila - Follow the Thief",
    [0x196cf] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/Battlesquid - First Prize",
    [0x196d0] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/Battlesquid - Second Prize",
    [0x196d1] = "@The Great Sea (Deprecated)/Windfall Island - Minigames/Battlesquid - Under 20 Shots Prize",
    [0x196d2] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Pompie and Vera - Secret Meeting Photo",
    [0x196d3] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Kamo - Full Moon Photo",
    [0x196d4] = "@The Great Sea (Deprecated)/Windfall Island - Short Sidequests/Minenco - Miss Windfall Photo",
    [0x196d5] = "@The Great Sea (Deprecated)/Windfall Island - Long Sidequests/Linda and Anton",

    [0x196d6] = "@The Great Sea/Dragon Roost Island Sector/Dragon Roost Island/Wind Shrine",
    [0x196d7] = "@The Great Sea/Dragon Roost Island Sector/Dragon Roost Island/Rito Aerie - Give Hoskit 20 Golden Feathers",
    [0x196d8] = "@The Great Sea/Dragon Roost Island Sector/Dragon Roost Island/Chest on Top of Boulder",
    [0x196d9] = "@The Great Sea/Dragon Roost Island Sector/Dragon Roost Island/Fly Across Platforms Around Island",
    [0x196da] = "@The Great Sea/Dragon Roost Island Sector/Dragon Roost Island/Rito Aerie - Mail Sorting",
    [0x196db] = "@The Great Sea/Dragon Roost Island Sector/Dragon Roost Island/Secret Cave",

    [0x196dc] = "@Dragon Roost Cavern/First Room",
    [0x196dd] = "@Dragon Roost Cavern/Alcove With Water Jugs",
    [0x196de] = "@Dragon Roost Cavern/Water Jug on Upper Shelf",
    [0x196df] = "@Dragon Roost Cavern/Boarded Up Chest",
    [0x196e0] = "@Dragon Roost Cavern/Chest Across Lava Pit",
    [0x196e1] = "@Dragon Roost Cavern/Rat Room",
    [0x196e2] = "@Dragon Roost Cavern/Rat Room Boarded Up Chest",
    [0x196e3] = "@Dragon Roost Cavern/Bird's Nest",
    [0x196e4] = "@Dragon Roost Cavern/Dark Room",
    [0x196e5] = "@Dragon Roost Cavern/Tingle Statue in Hub Room",
    [0x196e6] = "@Dragon Roost Cavern/Pot on Upper Shelf in Pot Room",
    [0x196e7] = "@Dragon Roost Cavern/Pot Room Chest",
    [0x196e8] = "@Dragon Roost Cavern/Miniboss",
    [0x196e9] = "@Dragon Roost Cavern/Under Rope Bridge",
    [0x196ea] = "@Dragon Roost Cavern/Tingle Statue Chest",
    [0x196eb] = "@Dragon Roost Cavern/Big Key Chest",
    [0x196ed] = "@Dragon Roost Cavern/Boss Stairs Left Chest",
    [0x196ec] = "@Dragon Roost Cavern/Boss Stairs Right Chest",
    [0x196ee] = "@Dragon Roost Cavern/Boss Stairs Right Pot",
    [0x196ef] = "@Dragon Roost Cavern/Gohma Heart Container",

    [0x196f0] = "@The Great Sea/Forest Haven Sector/Forest Haven/On Tree Branch",
    [0x196f1] = "@The Great Sea/Forest Haven Sector/Forest Haven/Small Island Chest",

    [0x196f2] = "@Forbidden Woods/First Room",
    [0x196f3] = "@Forbidden Woods/Inside Hollow Tree's Mouth",
    [0x196f4] = "@Forbidden Woods/Climb to Top Using Boko Baba Bulbs",
    [0x196f5] = "@Forbidden Woods/Pot High Above Hollow Tree",
    [0x196f6] = "@Forbidden Woods/Hole in Tree",
    [0x196f7] = "@Forbidden Woods/Morth Pit",
    [0x196f8] = "@Forbidden Woods/Vine Maze Left Chest",
    [0x196f9] = "@Forbidden Woods/Vine Maze Right Chest",
    [0x196fa] = "@Forbidden Woods/Highest Pot in Vine Maze",
    [0x196fb] = "@Forbidden Woods/Tall Room Before Miniboss",
    [0x196fc] = "@Forbidden Woods/Mothula Miniboss Room",
    [0x196fd] = "@Forbidden Woods/Past Seeds Hanging by Vines",
    [0x196fe] = "@Forbidden Woods/Chest Across Red Hanging Flower",
    [0x196ff] = "@Forbidden Woods/Tingle Statue Chest",
    [0x19700] = "@Forbidden Woods/Chest in Locked Tree Trunk",
    [0x19701] = "@Forbidden Woods/Big Key Chest",
    [0x19702] = "@Forbidden Woods/Double Mothula Room",
    [0x19703] = "@Forbidden Woods/Kalle Demos Heart Container",

    [0x19704] = "@The Great Sea/Greatfish Isle Sector/Greatfish Isle - Hidden Chest/",

    [0x19705] = "@Tower of the Gods/Chest Behind Bombable Walls",
    [0x19706] = "@Tower of the Gods/Pot Behind Bombable Walls",
    [0x19707] = "@Tower of the Gods/Hop Across Floating Boxes",
    [0x19708] = "@Tower of the Gods/Light Two Torches",
    [0x19709] = "@Tower of the Gods/Skulls Room Chest",
    [0x1970a] = "@Tower of the Gods/Shoot Eye Above Skulls Room Chest",
    [0x1970b] = "@Tower of the Gods/Tingle Statue Chest",
    [0x1970c] = "@Tower of the Gods/First Chest Guarded by Armos Knights",
    [0x1970d] = "@Tower of the Gods/Stone Tablet",
    [0x1970e] = "@Tower of the Gods/Darknut Miniboss Room",
    [0x1970f] = "@Tower of the Gods/Second Chest Guarded by Armos Knights",
    [0x19710] = "@Tower of the Gods/Floating Platforms Room",
    [0x19711] = "@Tower of the Gods/Top of Floating Platforms Room",
    [0x19712] = "@Tower of the Gods/Eastern Pot in Big Key Chest Room",
    [0x19713] = "@Tower of the Gods/Big Key Chest",
    [0x19714] = "@Tower of the Gods/Gohdan Heart Container",

    [0x19715] = "@The Great Sea/Tower of the Gods Sector/Hyrule/Master Sword Chamber",
    [0x19748] = "@The Great Sea/Tower of the Gods Sector/Hyrule/Ganon's Tower - Maze Chest",

    [0x19749] = "@The Great Sea (Deprecated)/Mailbox/Letter from Hoskit's Girlfriend",
    [0x1974a] = "@The Great Sea (Deprecated)/Mailbox/Letter from Baito's Mother",
    [0x1974b] = "@The Great Sea (Deprecated)/Mailbox/Letter from Baito",
    [0x1974c] = "@The Great Sea (Deprecated)/Mailbox/Letter from Komali's Father",
    [0x1974d] = "@The Great Sea (Deprecated)/Mailbox/Letter Advertising Bombs in Beedle's Shop",
    [0x1974e] = "@The Great Sea (Deprecated)/Mailbox/Letter Advertising Rock Spire Shop Ship",
    [0x19751] = "@The Great Sea (Deprecated)/Mailbox/Letter from Orca",
    [0x19752] = "@The Great Sea (Deprecated)/Mailbox/Letter from Grandma",
    [0x19753] = "@The Great Sea (Deprecated)/Mailbox/Letter from Aryll",
    [0x19754] = "@The Great Sea (Deprecated)/Mailbox/Letter from Tingle",

    [0x19716] = "@Forsaken Fortress/Phantom Ganon",
    [0x19717] = "@Forsaken Fortress/Chest Outside Upper Jail Cell",
    [0x19718] = "@Forsaken Fortress/Chest Inside Lower Jail Cell",
    [0x19719] = "@Forsaken Fortress/Chest Guarded by Bokoblin",
    [0x1971a] = "@Forsaken Fortress/Chest on Bed",
    [0x1971b] = "@Forsaken Fortress/Helmaroc King Heart Container",

    [0x1971c] = "@The Great Sea/Mother and Child Isles Sector/Mother and Child Isles - Inside Mother Isle/",

    [0x1971d] = "@The Great Sea/Fire Mountain Sector/Fire Mountain - Cave - Chest/",
    [0x1971e] = "@The Great Sea/Fire Mountain Sector/Fire Mountain - Lookout Platform/Chest",
    [0x1971f] = "@The Great Sea/Fire Mountain Sector/Fire Mountain - Lookout Platform/Destroy the Cannons",
    [0x19720] = "@The Great Sea/Fire Mountain Sector/Fire Mountain - Big Octo/",

    [0x19721] = "@The Great Sea/Ice Ring Isle Sector/Ice Ring Isle/Frozen Chest",
    [0x19722] = "@The Great Sea/Ice Ring Isle Sector/Ice Ring Isle/Cave - Chest",
    [0x19723] = "@The Great Sea/Ice Ring Isle Sector/Ice Ring Isle/Inner Cave - Chest",

    [0x19724] = "@The Great Sea/Headstone Island Sector/Headstone Island - Top of the Island/",
    [0x19725] = "@The Great Sea/Headstone Island Sector/Headstone Island - Submarine/",

    [0x19726] = "@Earth Temple/Transparent Chest In Warp Pot Room",
    [0x19727] = "@Earth Temple/Behind Curtain In Warp Pot Room",
    [0x19728] = "@Earth Temple/Transparent Chest in First Crypt",
    [0x19729] = "@Earth Temple/Chest Behind Destructible Walls",
    [0x1972a] = "@Earth Temple/Chest In Three Blocks Room",
    [0x1972b] = "@Earth Temple/Chest Behind Statues",
    [0x1972c] = "@Earth Temple/Casket in Second Crypt",
    [0x1972d] = "@Earth Temple/Stalfos Miniboss Room",
    [0x1972e] = "@Earth Temple/Tingle Statue Chest",
    [0x1972f] = "@Earth Temple/End of Foggy Room With Floormasters",
    [0x19730] = "@Earth Temple/Kill All Floormasters in Foggy Room",
    [0x19731] = "@Earth Temple/Behind Curtain Next to Hammer Button",
    [0x19732] = "@Earth Temple/Chest in Third Crypt",
    [0x19733] = "@Earth Temple/Many Mirrors Room Right Chest",
    [0x19734] = "@Earth Temple/Many Mirrors Room Left Chest",
    [0x19735] = "@Earth Temple/Stalfos Crypt Room",
    [0x19736] = "@Earth Temple/Big Key Chest",
    [0x19737] = "@Earth Temple/Jalhalla Heart Container",

    [0x19738] = "@Wind Temple/Chest Between Two Dirt Patches",
    [0x19739] = "@Wind Temple/Behind Stone Head in Hidden Upper Room",
    [0x1973a] = "@Wind Temple/Tingle Statue Chest",
    [0x1973b] = "@Wind Temple/Chest Behind Stone Head",
    [0x1973c] = "@Wind Temple/Chest in Left Alcove",
    [0x1973d] = "@Wind Temple/Big Key Chest",
    [0x1973e] = "@Wind Temple/Chest In Many Cyclones Room",
    [0x1973f] = "@Wind Temple/Behind Stone Head in Many Cyclones Room",
    [0x19740] = "@Wind Temple/Chest In Middle of Hub Room",
    [0x19741] = "@Wind Temple/Spike Wall Room - First Chest",
    [0x19742] = "@Wind Temple/Spike Wall Room - Destroy All Cracked Floors",
    [0x19743] = "@Wind Temple/Wizzrobe Miniboss Room",
    [0x19744] = "@Wind Temple/Chest at Top of Hub Room",
    [0x19745] = "@Wind Temple/Chest Behind Seven Armos",
    [0x19746] = "@Wind Temple/Kill All Enemies in Tall Basement Room",
    [0x19747] = "@Wind Temple/Molgera Heart Container",

    [0x19755] = "@The Great Sea (Deprecated)/Great Sea/Beedle's Shop Ship - 20 Rupee Item",
    [0x19756] = "@The Great Sea (Deprecated)/Great Sea/Salvage Corp Gift",
    [0x19757] = "@The Great Sea (Deprecated)/Great Sea/Cyclos",
    [0x19758] = "@The Great Sea (Deprecated)/Great Sea/Goron Trading Reward",
    [0x19759] = "@The Great Sea (Deprecated)/Great Sea/Withered Trees",
    [0x1975a] = "@The Great Sea (Deprecated)/Great Sea/Ghost Ship",

    [0x1975b] = "@The Great Sea/Private Oasis Sector/Private Oasis/Chest at Top of Waterfall",
    [0x1975c] = "@The Great Sea/Private Oasis Sector/Private Oasis/Cabana Labyrinth - Lower Floor Chest",
    [0x1975d] = "@The Great Sea/Private Oasis Sector/Private Oasis/Cabana Labyrinth - Upper Floor Chest",
    [0x1975e] = "@The Great Sea/Private Oasis Sector/Private Oasis - Big Octo/",

    [0x1975f] = "@The Great Sea/Spectacle Island Sector/Spectacle Island/Barrel Shooting - First Prize",
    [0x19760] = "@The Great Sea/Spectacle Island Sector/Spectacle Island/Barrel Shooting - Second Prize",

    [0x19761] = "@The Great Sea/Needle Rock Isle Sector/Needle Rock Isle/Chest in Ring of Fire",
    [0x19762] = "@The Great Sea/Needle Rock Isle Sector/Needle Rock Isle/Cave",
    [0x19763] = "@The Great Sea/Needle Rock Isle Sector/Needle Rock Isle - Golden Gunboat/",

    [0x19764] = "@The Great Sea/Angular Isles Sector/Angular Isles/Peak",
    [0x19765] = "@The Great Sea/Angular Isles Sector/Angular Isles/Cave",

    [0x19766] = "@The Great Sea/Boating Course Sector/Boating Course - Raft/",
    [0x19767] = "@The Great Sea/Boating Course Sector/Boating Course - Cave/",

    [0x19768] = "@The Great Sea/Stone Watcher Island Sector/Stone Watcher Island - Cave/",
    [0x19769] = "@The Great Sea/Stone Watcher Island Sector/Stone Watcher Island - Lookout Platform/Chest",
    [0x1976a] = "@The Great Sea/Stone Watcher Island Sector/Stone Watcher Island - Lookout Platform/Destroy the Cannons",

    [0x1976b] = "@The Great Sea/Islet of Steel Sector/Islet of Steel - Interior/",
    [0x1976c] = "@The Great Sea/Islet of Steel Sector/Islet of Steel - Lookout Platform - Defeat the Enemies/",

    [0x1976d] = "@The Great Sea/Overlook Island Sector/Overlook Island - Cave/",

    [0x1976e] = "@The Great Sea/Bird's Peak Rock Sector/Bird's Peak Rock - Cave/",

    [0x1976f] = "@The Great Sea/Pawprint Isle Sector/Pawprint Isle/Chuchu Cave - Chest",
    [0x19770] = "@The Great Sea/Pawprint Isle Sector/Pawprint Isle/Chuchu Cave - Behind Left Boulder",
    [0x19771] = "@The Great Sea/Pawprint Isle Sector/Pawprint Isle/Chuchu Cave - Behind Right Boulder",
    [0x19772] = "@The Great Sea/Pawprint Isle Sector/Pawprint Isle/Chuchu Cave - Scale the Wall",
    [0x19773] = "@The Great Sea/Pawprint Isle Sector/Pawprint Isle/Wizzrobe Cave",
    [0x19774] = "@The Great Sea/Pawprint Isle Sector/Pawprint Isle - Lookout Platform - Defeat the Enemies/",

    [0x19775] = "@The Great Sea/Thorned Fairy Island Sector/Thorned Fairy Island - Great Fairy/",
    [0x19776] = "@The Great Sea/Thorned Fairy Island Sector/Thorned Fairy Island - Lookout Platforms/Northeastern Lookout Platform - Destroy the Cannons",
    [0x19777] = "@The Great Sea/Thorned Fairy Island Sector/Thorned Fairy Island - Lookout Platforms/Southwestern Lookout Platform - Defeat the Enemies",

    [0x19778] = "@The Great Sea/Eastern Fairy Island Sector/Eastern Fairy Island - Great Fairy/",
    [0x19779] = "@The Great Sea/Eastern Fairy Island Sector/Eastern Fairy Island - Lookout Platform - Defeat the Cannons and Enemies/",

    [0x1977a] = "@The Great Sea/Western Fairy Island Sector/Western Fairy Island - Great Fairy/",
    [0x1977b] = "@The Great Sea/Western Fairy Island Sector/Western Fairy Island - Lookout Platform/",

    [0x1977c] = "@The Great Sea/Southern Fairy Island Sector/Southern Fairy Island - Great Fairy/",
    [0x1977d] = "@The Great Sea/Southern Fairy Island Sector/Southern Fairy Island - Lookout Platform/Destroy the Northwest Cannons",
    [0x1977e] = "@The Great Sea/Southern Fairy Island Sector/Southern Fairy Island - Lookout Platform/Destroy the Southeast Cannons",

    [0x1977f] = "@The Great Sea/Northern Fairy Island Sector/Northern Fairy Island - Great Fairy/",
    [0x19780] = "@The Great Sea/Northern Fairy Island Sector/Northern Fairy Island - Submarine/",

    [0x19781] = "@The Great Sea/Tingle Island Sector/Tingle Island - Ankle - Reward for All Tingle Statues/",
    [0x19782] = "@The Great Sea/Tingle Island Sector/Tingle Island - Big Octo/",

    [0x19783] = "@The Great Sea/Diamond Steppe Island Sector/Diamond Steppe Island - Warp Maze Cave/First Chest",
    [0x19784] = "@The Great Sea/Diamond Steppe Island Sector/Diamond Steppe Island - Warp Maze Cave/Second Chest",
    [0x19785] = "@The Great Sea/Diamond Steppe Island Sector/Diamond Steppe Island - Big Octo/",

    [0x19786] = "@The Great Sea/Bomb Island Sector/Bomb Island - Cave/",
    [0x19787] = "@The Great Sea/Bomb Island Sector/Bomb Island - Lookout Platform - Defeat the Enemies/",
    [0x19788] = "@The Great Sea/Bomb Island Sector/Bomb Island - Submarine/",

    [0x19789] = "@The Great Sea/Rock Spire Isle Sector/Rock Spire Isle/Cave",
    [0x1978a] = "@The Great Sea/Rock Spire Isle Sector/Rock Spire Isle/Beedle's Special Shop Ship - 500 Item",
    [0x1978b] = "@The Great Sea/Rock Spire Isle Sector/Rock Spire Isle/Beedle's Special Shop Ship - 950 Item",
    [0x1978c] = "@The Great Sea/Rock Spire Isle Sector/Rock Spire Isle/Beedle's Special Shop Ship - 900 Item",
    [0x1978d] = "@The Great Sea/Rock Spire Isle Sector/Rock Spire Isle - Lookout Platforms/Western Lookout Platform - Destroy the Cannons",
    [0x1978e] = "@The Great Sea/Rock Spire Isle Sector/Rock Spire Isle - Lookout Platforms/Eastern Lookout Platform - Destroy the Cannons",
    [0x1978f] = "@The Great Sea/Rock Spire Isle Sector/Rock Spire Isle - Lookout Platforms/Center Lookout Platform",
    [0x19790] = "@The Great Sea/Rock Spire Isle Sector/Rock Spire Isle - Southeast Gunboat/",

    [0x19791] = "@The Great Sea/Shark Island Sector/Shark Island - Cave/",

    [0x19792] = "@The Great Sea/Cliff Plateau Isles Sector/Cliff Plateau Isles/Cave",
    [0x19793] = "@The Great Sea/Cliff Plateau Isles Sector/Cliff Plateau Isles/Highest Isle",
    [0x19794] = "@The Great Sea/Cliff Plateau Isles Sector/Cliff Plateau Isles - Lookout Platform/",

    [0x19795] = "@The Great Sea/Crescent Moon Island Sector/Crescent Moon Island - Chest/",
    [0x19796] = "@The Great Sea/Crescent Moon Island Sector/Crescent Moon Island - Submarine/",

    [0x19797] = "@The Great Sea/Horseshoe Island Sector/Horseshoe Island/Play Golf",
    [0x19798] = "@The Great Sea/Horseshoe Island Sector/Horseshoe Island/Cave",
    [0x19799] = "@The Great Sea/Horseshoe Island Sector/Horseshoe Island - Lookout Platforms/Northwestern Lookout Platform",
    [0x1979a] = "@The Great Sea/Horseshoe Island Sector/Horseshoe Island - Lookout Platforms/Southeastern Lookout Platform",

    [0x1979b] = "@The Great Sea/Flight Control Platform Sector/Flight Control Platform - Bird-Man Content - First Prize/",
    [0x1979c] = "@The Great Sea/Flight Control Platform Sector/Flight Control Platform - Submarine/",

    [0x1979e] = "@The Great Sea/Star Island Sector/Star Island - Lookout Platform/",
    [0x1979d] = "@The Great Sea/Star Island Sector/Star Island - Cave/",

    [0x1979f] = "@The Great Sea/Star Belt Archipelago Sector/Star Belt Archipelago - Lookout Platform/",

    [0x197a1] = "@The Great Sea/Five-Star Isles Sector/Five-Star Isles - Raft/",
    [0x197a2] = "@The Great Sea/Five-Star Isles Sector/Five-Star Isles - Submarine/",
    [0x197a0] = "@The Great Sea/Five-Star Isles Sector/Five-Star Isles - Lookout Platform - Destroy the Cannons/",

    [0x197a3] = "@The Great Sea/Seven-Star Isles Sector/Seven-Star Isles - Lookout Platforms/Center Lookout Platform",
    [0x197a4] = "@The Great Sea/Seven-Star Isles Sector/Seven-Star Isles - Lookout Platforms/Northern Lookout Platform",
    [0x197a5] = "@The Great Sea/Seven-Star Isles Sector/Seven-Star Isles - Lookout Platforms/Southern Lookout Platform",
    [0x197a6] = "@The Great Sea/Seven-Star Isles Sector/Seven-Star Isles - Big Octo/",

    [0x197a7] = "@The Great Sea/Cyclops Reef Sector/Cyclops Reef - Destroy the Cannons and Gunboats/",
    [0x197a8] = "@The Great Sea/Cyclops Reef Sector/Cyclops Reef - Lookout Platform - Defeat the Enemies/",

    [0x197a9] = "@The Great Sea/Two-Eye Reef Sector/Two-Eye Reef - Destroy the Cannons and Gunboats/",
    [0x197aa] = "@The Great Sea/Two-Eye Reef Sector/Two-Eye Reef - Lookout Platform/",
    [0x197ab] = "@The Great Sea/Two-Eye Reef Sector/Two-Eye Reef - Big Octo Great Fairy/",

    [0x197ac] = "@The Great Sea/Three-Eye Reef Sector/Three-Eye Reef - Destroy the Cannons and Gunboats/",

    [0x197ad] = "@The Great Sea/Four-Eye Reef Sector/Four-Eye Reef - Destroy the Cannons and Gunboats/",

    [0x197ae] = "@The Great Sea/Five-Eye Reef Sector/Five-Eye Reef - Destroy the Cannons/",
    [0x197af] = "@The Great Sea/Five-Eye Reef Sector/Five-Eye Reef - Lookout Platform/",

    [0x197b0] = "@The Great Sea/Six-Eye Reef Sector/Six-Eye Reef - Destroy the Cannons and Gunboats/",
    [0x197b1] = "@The Great Sea/Six-Eye Reef Sector/Six-Eye Reef - Lookout Platform - Destroy the Cannons/",
    [0x197b2] = "@The Great Sea/Six-Eye Reef Sector/Six-Eye Reef - Submarine/",

    [0x197b3] = "@Treasure Salvaging/Forsaken Fortress Sector - Sunken Treasure 25/Salvage",
    [0x197b4] = "@Treasure Salvaging/Star Island - Sunken Treasure 7/Salvage",
    [0x197b5] = "@Treasure Salvaging/Northern Fairy Island - Sunken Treasure 24/Salvage",
    [0x197b7] = "@Treasure Salvaging/Crescent Moon Island - Sunken Treasure 11/Salvage",
    [0x197b9] = "@Treasure Salvaging/Overlook Island - Sunken Treasure 13/Salvage",
    [0x197ba] = "@Treasure Salvaging/Four-Eye Reef - Sunken Treasure 41/Salvage",
    [0x197bb] = "@Treasure Salvaging/Mother and Child Isles - Sunken Treasure 29/Salvage",
    [0x197bc] = "@Treasure Salvaging/Spectacle Island - Sunken Treasure 22/Salvage",
    [0x197bd] = "@Treasure Salvaging/Windfall Island - Sunken Treasure 18/Salvage",
    [0x197be] = "@Treasure Salvaging/Pawprint Isle - Sunken Treasure 30/Salvage",
    [0x197bf] = "@Treasure Salvaging/Dragon Roost Island - Sunken Treasure 39/Salvage",
    [0x197c0] = "@Treasure Salvaging/Flight Control Platform - Sunken Treasure 19/Salvage",
    [0x197c1] = "@Treasure Salvaging/Western Fairy Island - Sunken Treasure 8/Salvage",
    [0x197c2] = "@Treasure Salvaging/Rock Spire Isle - Sunken Treasure 2/Salvage",
    [0x197c3] = "@Treasure Salvaging/Tingle Island - Sunken Treasure 10/Salvage",
    [0x197c4] = "@Treasure Salvaging/Northern Triangle Island - Sunken Treasure 26/Salvage",
    [0x197c5] = "@Treasure Salvaging/Eastern Fairy Island - Sunken Treasure 3/Salvage",
    [0x197c6] = "@Treasure Salvaging/Fire Mountain - Sunken Treasure 37/Salvage",
    [0x197c7] = "@Treasure Salvaging/Star Belt Archipelago - Sunken Treasure 27/Salvage",
    [0x197c8] = "@Treasure Salvaging/Three-Eye Reef - Sunken Treasure 38/Salvage",
    [0x197ca] = "@Treasure Salvaging/Cyclops Reef - Sunken Treasure 21/Salvage",
    [0x197cb] = "@Treasure Salvaging/Six-Eye Reef - Sunken Treasure 6/Salvage",
    [0x197cc] = "@Treasure Salvaging/Tower of The Gods Sector - Sunken Treasure 14/Salvage",
    [0x197cd] = "@Treasure Salvaging/Eastern Triangle Island - Sunken Treasure 34/Salvage",
    [0x197ce] = "@Treasure Salvaging/Thorned Fairy Island - Sunken Treasure 5/Salvage",
    [0x197cf] = "@Treasure Salvaging/Needle Rock Isle - Sunken Treasure 28/Salvage",
    [0x197d0] = "@Treasure Salvaging/Islet of Steel - Sunken Treasure 35/Salvage",
    [0x197d3] = "@Treasure Salvaging/Private Oasis - Sunken Treasure 1/Salvage",
    [0x197d4] = "@Treasure Salvaging/Bomb Island - Sunken Treasure 20/Salvage",
    [0x197d5] = "@Treasure Salvaging/Bird's Peak Rock - Sunken Treasure 36/Salvage",
    [0x197d6] = "@Treasure Salvaging/Diamond Steppe Island - Sunken Treasure 23/Salvage",
    [0x197d7] = "@Treasure Salvaging/Five-Eye Reef - Sunken Treasure 12/Salvage",
    [0x197d8] = "@Treasure Salvaging/Shark Island - Sunken Treasure 16/Salvage",
    [0x197d9] = "@Treasure Salvaging/Southern Fairy Island - Sunken Treasure 4/Salvage",
    [0x197da] = "@Treasure Salvaging/Ice Ring Isle - Sunken Treasure 17/Salvage",
    [0x197db] = "@Treasure Salvaging/Forest Haven - Sunken Treasure 31/Salvage",
    [0x197dd] = "@Treasure Salvaging/Horseshoe Island - Sunken Treasure 9/Salvage",
    [0x197df] = "@Treasure Salvaging/Headstone Island - Sunken Treasure 40/Salvage",
    [0x197e1] = "@Treasure Salvaging/Angular Isles - Sunken Treasure 15/Salvage",
    [0x197e2] = "@Treasure Salvaging/Boating Course - Sunken Treasure 32/Salvage",
    [0x197e3] = "@Treasure Salvaging/Five-Star Isles - Sunken Treasure 33/Salvage",

    [0x197b6] = "@Treasure Salvaging/Gale Isle - Sunken Treasure 42/Salvage",
    [0x197b8] = "@Treasure Salvaging/Seven-Star Isles - Sunken Treasure 45/Salvage",

    [0x197c9] = "@Triforce Salvaging/Greatfish Isle - Sunken Triforce 1/Salvage",
    [0x197d1] = "@Triforce Salvaging/Stone Watcher Island - Sunken Triforce 2/Salvage",

    [0x197d2] = "@Treasure Salvaging/Southern Triangle Island - Sunken Treasure 44/Salvage",

    [0x197dc] = "@Triforce Salvaging/Cliff Plateau Isles - Sunken Triforce 3/Salvage",

    [0x197de] = "@Treasure Salvaging/Outset island - Sunken Treasure 43/Salvage",
    [0x197e0] = "@Treasure Salvaging/Two-Eye Reef - Sunken Treasure 46/Salvage",
}
